newrelic/docs-website,820401165,1099,"{'number': 1099.0, 'repo': 'docs-website', 'user_login': 'newrelic'}","[{'action': 'opened', 'author': 'solson2009', 'comment_id': None, 'datetime': '2021-03-02T21:22:07Z', 'masked_author': 'username_0', 'text': ""Updated as per instructions in training üòÉ\r\n\r\n<!-- Thanks for contributing to our docs! Your changes will help thousands of\r\nNew Relic users around the world. -->\r\n\r\n<!-- Fill out this template to help us review your changes and route them to the\r\nbest team. See our [README.md](https://github.com/newrelic/docs-website/) for \r\ninformation on how to contribute. -->\r\n\r\n### Tell us why\r\n\r\nExplain why you're proposing this change. If there's an existing GitHub issue \r\nrelated to your change, please link to it.\r\n\r\n### Anything else you'd like to share?\r\n\r\nAdd any context that will help us review your changes such as testing notes,\r\nlinks to related docs, screenshots, etc. \r\n\r\n### Are you making a change to site code?\r\n\r\nIf you're changing site code (rather than the content of a doc), please follow\r\n[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/) \r\nin your commit messages and pull request title."", 'title': 'Update nrdb-horsepower-under-hood.mdx', 'type': 'issue'}]","<issue_start><issue_comment>Title: Update nrdb-horsepower-under-hood.mdx
username_0: Updated as per instructions in training üòÉ

<!-- Thanks for contributing to our docs! Your changes will help thousands of
New Relic users around the world. -->

<!-- Fill out this template to help us review your changes and route them to the
best team. See our [README.md](https://github.com/newrelic/docs-website/) for 
information on how to contribute. -->

### Tell us why

Explain why you're proposing this change. If there's an existing GitHub issue 
related to your change, please link to it.

### Anything else you'd like to share?

Add any context that will help us review your changes such as testing notes,
links to related docs, screenshots, etc. 

### Are you making a change to site code?

If you're changing site code (rather than the content of a doc), please follow
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/) 
in your commit messages and pull request title."
eduardoboucas/staticman,651220220,361,,"[{'action': 'opened', 'author': 'sirinath', 'comment_id': None, 'datetime': '2020-07-06 03:25:38+00:00', 'masked_author': 'username_0', 'text': ""Is it possible to maybe liaison with GitHub/GitLab to remove API limits? This will be more convenient than hosting one's own instance.\r\n\r\nAlso, get sponsorship from them or another provider supporting static sites towards the Staticman site hosting if hosting bandwidth and power is a limiting factor."", 'title': 'Appeal to Remove API Limits and Get Support Towards Hosted Instance of Staticman', 'type': 'issue'}
 {'action': 'created', 'author': 'alexwaibel', 'comment_id': 654291352.0, 'datetime': '2020-07-06 15:00:16+00:00', 'masked_author': 'username_1', 'text': 'The issue is not an API limit from GitHub. The reason the public instance was discontinued was that it was hosted on the free tier of Heroku which has low usage limit. With multiple people trying to use the same public instance, we quickly exhausted the limits of that Heroku tier. This is a community project with no funding so unless we find someone to pay for a public instance, the best alternative is to streamline the Staticman setup process and encourage users to host their own free instance.\r\n\r\nSponsorship is something we are open to, however I currently do not have the time to go out and search for such a sponsor.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'sirinath', 'comment_id': 654302129.0, 'datetime': '2020-07-06 15:19:24+00:00', 'masked_author': 'username_0', 'text': 'You can just ask Heroku to remove the limits. If they do then great win for everyone.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'alexwaibel', 'comment_id': 654324473.0, 'datetime': '2020-07-06 15:59:53+00:00', 'masked_author': 'username_1', 'text': ""Heroku is a business and has no incentive to offer us unlimited free hosting for nothing in return. We don't really have any leverage in this situation."", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'sirinath', 'comment_id': 654325651.0, 'datetime': '2020-07-06 16:01:58+00:00', 'masked_author': 'username_0', 'text': 'You can put a sponsored by Heroku on the website and the readme.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'sirinath', 'comment_id': 654331186.0, 'datetime': '2020-07-06 16:12:33+00:00', 'masked_author': 'username_0', 'text': 'Companies like GitHub, GitLab, Zeit, Netlify may have the incentive to host it as this will increase adaptation of their services and will be added benefit to their clients.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'alexwaibel', 'comment_id': 654337258.0, 'datetime': '2020-07-06 16:23:54+00:00', 'masked_author': 'username_1', 'text': ""As mentioned before, I personally don't currently have the time to seek out such potential sponsorships so this is not something I plan to pursue. This project is currently in a kind of a maintenance mode where I attempt to get to critical bug fixes in a timely manner but don't have the bandwidth to add features and expand the project further right now. If we get some more maintainers and development of this project picks up steam, then I think we would be in a better position to seek sponsorship. If anyone is interested in such a role, we will happily accept contributions.\r\n\r\nHaving a sponsor places certain expectations on the project (especially regarding feature development) and this is just not something we're in a position to commit to at this time."", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'VincentTam', 'comment_id': 792634755.0, 'datetime': '2021-03-08 09:56:53+00:00', 'masked_author': 'username_2', 'text': ""With the one-click deploy button and the updated tutorials, hosting on a free-tier Heroku should be incredibly convenient with no installation at all.\r\n\r\nTake Git*'s API limit as the fuse box of your floor.  In case of a short circuit (say sœÅŒ±m), the circuit has to be cut.  As a commenting service hosted on a particular instance can be used by everyone, this safety guard has to be put in place."", 'title': None, 'type': 'comment'}]","<issue_start><issue_comment>Title: Appeal to Remove API Limits and Get Support Towards Hosted Instance of Staticman
username_0: Is it possible to maybe liaison with GitHub/GitLab to remove API limits? This will be more convenient than hosting one's own instance.

Also, get sponsorship from them or another provider supporting static sites towards the Staticman site hosting if hosting bandwidth and power is a limiting factor.
<issue_comment>username_1: The issue is not an API limit from GitHub. The reason the public instance was discontinued was that it was hosted on the free tier of Heroku which has low usage limit. With multiple people trying to use the same public instance, we quickly exhausted the limits of that Heroku tier. This is a community project with no funding so unless we find someone to pay for a public instance, the best alternative is to streamline the Staticman setup process and encourage users to host their own free instance.

Sponsorship is something we are open to, however I currently do not have the time to go out and search for such a sponsor.
<issue_comment>username_0: You can just ask Heroku to remove the limits. If they do then great win for everyone.
<issue_comment>username_1: Heroku is a business and has no incentive to offer us unlimited free hosting for nothing in return. We don't really have any leverage in this situation.
<issue_comment>username_0: You can put a sponsored by Heroku on the website and the readme.
<issue_comment>username_0: Companies like GitHub, GitLab, Zeit, Netlify may have the incentive to host it as this will increase adaptation of their services and will be added benefit to their clients.
<issue_comment>username_1: As mentioned before, I personally don't currently have the time to seek out such potential sponsorships so this is not something I plan to pursue. This project is currently in a kind of a maintenance mode where I attempt to get to critical bug fixes in a timely manner but don't have the bandwidth to add features and expand the project further right now. If we get some more maintainers and development of this project picks up steam, then I think we would be in a better position to seek sponsorship. If anyone is interested in such a role, we will happily accept contributions.

Having a sponsor places certain expectations on the project (especially regarding feature development) and this is just not something we're in a position to commit to at this time.
<issue_comment>username_2: With the one-click deploy button and the updated tutorials, hosting on a free-tier Heroku should be incredibly convenient with no installation at all.

Take Git*'s API limit as the fuse box of your floor.  In case of a short circuit (say sœÅŒ±m), the circuit has to be cut.  As a commenting service hosted on a particular instance can be used by everyone, this safety guard has to be put in place."
dlang/dlang.org,305922269,2277,"{'number': 2277.0, 'repo': 'dlang.org', 'user_login': 'dlang'}","[{'action': 'opened', 'author': 'JinShil', 'comment_id': None, 'datetime': '2018-03-16T13:11:24Z', 'masked_author': 'username_0', 'text': '`delete` was deprecated in 2.079.  Before the `delete` keyword can be removed it will be necessary to also deprecate and remove class allocators and deallocators.  They have been planned for deprecation for years; this PR finally puts the deprecation process in motion.\r\n\r\nSee https://dlang.org/deprecate.html#Class%20allocators%20and%20deallocators\r\n\r\nDMD PR:  https://github.com/dlang/dmd/pull/8042', 'title': 'Deprecate class allocators and deallocators', 'type': 'issue'}
 {'action': 'created', 'author': 'adamdruppe', 'comment_id': 373713612.0, 'datetime': '2018-03-16 13:30:54+00:00', 'masked_author': 'username_1', 'text': 'So we recently found `@disable new` is actually kinda cool....', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'JinShil', 'comment_id': 373714050.0, 'datetime': '2018-03-16 13:32:48+00:00', 'masked_author': 'username_0', 'text': 'Please elaborate.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'adamdruppe', 'comment_id': 373715364.0, 'datetime': '2018-03-16 13:37:47+00:00', 'masked_author': 'username_1', 'text': '```\r\nstruct S\r\n{\r\n  @disable new (size_t s) { return null; }\r\n}\r\n\r\nvoid main()\r\n{\r\n\tS* s = new S; //  Error: allocator `e.S.new` is not callable because it is annotated with @disable\r\n}\r\n```', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'adamdruppe', 'comment_id': 373715994.0, 'datetime': '2018-03-16 13:40:12+00:00', 'masked_author': 'username_1', 'text': 'So the application there is you can force users to go through your custom factory functions, or in the case of structs, put them on the stack (or bypass with memcpy lol).', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'JackStouffer', 'comment_id': 373718495.0, 'datetime': '2018-03-16 13:49:30+00:00', 'masked_author': 'username_2', 'text': 'See https://github.com/dlang/phobos/pull/6003 for an example.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'JinShil', 'comment_id': 373834833.0, 'datetime': '2018-03-16 20:25:10+00:00', 'masked_author': 'username_0', 'text': ""I've added support for the syntax `@disable new();` to the DMD PR.  You won't even need to add the useless `size_t` argument.  That should prevent any breaking changes."", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'adamdruppe', 'comment_id': 373835584.0, 'datetime': '2018-03-16 20:27:58+00:00', 'masked_author': 'username_1', 'text': 'That sounds good to me!', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'JinShil', 'comment_id': 373888991.0, 'datetime': '2018-03-17 02:48:22+00:00', 'masked_author': 'username_0', 'text': 'Great!  If you don\'t mind, and truly approve of this PR, please take the explicit step of marking it ""Approved"".', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'adamdruppe', 'comment_id': 373889129.0, 'datetime': '2018-03-17 02:51:12+00:00', 'masked_author': 'username_1', 'text': ""oh lol i keep forgetting i actually have some power in this repo. I don't have such power over on the dmd side though."", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'JinShil', 'comment_id': 373889456.0, 'datetime': '2018-03-17 02:57:27+00:00', 'masked_author': 'username_0', 'text': 'I still think it\'s helpful to mark PRs ""approved"" even in repos where you may not have merge rights.  It helps to know that it was reviewed and scrutinized by anyone with D language skills, especially a veteran like yourself.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'wilzbach', 'comment_id': 373988978.0, 'datetime': '2018-03-18 10:58:54+00:00', 'masked_author': 'username_3', 'text': ""Shouldn't this PR remove or mark as deprecated the respective sections in the spec too?\r\ne.g.\r\nhttps://dlang.org/spec/class.html#allocators"", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'JinShil', 'comment_id': 373992927.0, 'datetime': '2018-03-18 12:01:48+00:00', 'masked_author': 'username_0', 'text': 'I remember a brief discussion we had with one of the other deprecations in 2.079 to leave the spec in tact until removal (See https://github.com/dlang/dlang.org/pull/1941#issuecomment-364106970) so users could still refer to it when updating their code.  Therefore, since the spec has already marked allocators and deallocators as deprecated, I think the spec should be left it as is until removal.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'JinShil', 'comment_id': 377780339.0, 'datetime': '2018-04-01 11:29:04+00:00', 'masked_author': 'username_0', 'text': 'Ping!  DMD PR was merged.', 'title': None, 'type': 'comment'}]","<issue_start><issue_comment>Title: Deprecate class allocators and deallocators
username_0: `delete` was deprecated in 2.079.  Before the `delete` keyword can be removed it will be necessary to also deprecate and remove class allocators and deallocators.  They have been planned for deprecation for years; this PR finally puts the deprecation process in motion.

See https://dlang.org/deprecate.html#Class%20allocators%20and%20deallocators

DMD PR:  https://github.com/dlang/dmd/pull/8042
<issue_comment>username_1: So we recently found `@disable new` is actually kinda cool....
<issue_comment>username_0: Please elaborate.
<issue_comment>username_1: ```
struct S
{
  @disable new (size_t s) { return null; }
}

void main()
{
	S* s = new S; //  Error: allocator `e.S.new` is not callable because it is annotated with @disable
}
```
<issue_comment>username_1: So the application there is you can force users to go through your custom factory functions, or in the case of structs, put them on the stack (or bypass with memcpy lol).
<issue_comment>username_2: See https://github.com/dlang/phobos/pull/6003 for an example.
<issue_comment>username_0: I've added support for the syntax `@disable new();` to the DMD PR.  You won't even need to add the useless `size_t` argument.  That should prevent any breaking changes.
<issue_comment>username_1: That sounds good to me!
<issue_comment>username_0: Great!  If you don't mind, and truly approve of this PR, please take the explicit step of marking it ""Approved"".
<issue_comment>username_1: oh lol i keep forgetting i actually have some power in this repo. I don't have such power over on the dmd side though.
<issue_comment>username_0: I still think it's helpful to mark PRs ""approved"" even in repos where you may not have merge rights.  It helps to know that it was reviewed and scrutinized by anyone with D language skills, especially a veteran like yourself.
<issue_comment>username_3: Shouldn't this PR remove or mark as deprecated the respective sections in the spec too?
e.g.
https://dlang.org/spec/class.html#allocators
<issue_comment>username_0: I remember a brief discussion we had with one of the other deprecations in 2.079 to leave the spec in tact until removal (See https://github.com/dlang/dlang.org/pull/1941#issuecomment-364106970) so users could still refer to it when updating their code.  Therefore, since the spec has already marked allocators and deallocators as deprecated, I think the spec should be left it as is until removal.
<issue_comment>username_0: Ping!  DMD PR was merged."
eduardoboucas/staticman,728491209,390,,"[{'action': 'opened', 'author': 'infominer33', 'comment_id': None, 'datetime': '2020-10-23 20:01:14+00:00', 'masked_author': 'username_0', 'text': ""hey! I really love staticman, thanks for all the hard work to those maintaining it! \r\n\r\nI've enabled encryption for the e-mail field and message field to use as a regular contact form.. now I'm trying to decrypt my first contact message sent thru staticman.\r\n\r\nfirst I tried:\r\n\r\n`openssl rsautl -decrypt -in /home/bob/encrypted -out /home/bob/decrypted -inkey /home/bob/.ssh/id_bot_rsa'\r\n\r\noutputs:\r\n```\r\nRSA operation error\r\n139704754267456:error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error:../crypto/rsa/rsa_pk1.c:251:\r\n139704754267456:error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:491:\r\n```\r\n\r\nthen I found this post by username_3 about [Staticman's Encryption Mechanism](https://vincenttam.gitlab.io/post/2018-12-25-staticman-encryption-mechanism/) and try changing my decrypted message to base64 but getting a similar error\r\n\r\ncat encrypted | base64 -d | openssl rsautl -decrypt -oaep -out /home/bob/decrypted -inkey /home/bob/.ssh/id_bot_rsa\r\n\r\n```\r\n140543979599168:error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error:../crypto/rsa/rsa_oaep.c:262:\r\n140543979599168:error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:491:\r\n```\r\n\r\nI didn't realize it would be this hard, or I would have tried decrypting before I got my first submission to this contact form üòÖ\r\n\r\nI plan to do this in python eventually.. so, I'm not married to this openssl method if you have a suggestion in a different direction.\r\n\r\nany help appreciated"", 'title': 'trouble decrypting encrypted comment fields', 'type': 'issue'}
 {'action': 'created', 'author': 'infominer33', 'comment_id': 715625723.0, 'datetime': '2020-10-23 23:04:57+00:00', 'masked_author': 'username_0', 'text': ""Ok, trying again after finding RSA.js.. I copied it's contents to decrypt.js in the root of my staticman project folder, on the server where it's hosted and modified it for this purpose:\r\n\r\n```\r\nconst NodeRSA = require('node-rsa')\r\nconst key = new NodeRSA()\r\nkey.importKey('-----BEGIN RSA PRIVATE KEY-----\\n Key found in config.production.json \\n-----END RSA PRIVATE KEY-----', 'private');\r\nconst decrypted = key.decrypt('539c27a0e4b4bfc25f45b2254245wergdsa10803f725', 'utf8');\r\nconsole.log('decrypted: ', decrypted); \r\n```\r\n\r\n`node decrypt.js`\r\n\r\noutputs:\r\n\r\n```\r\n/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:301\r\n            throw Error('Error during decryption (probably incorrect key). Original error: ' + e);\r\n            ^\r\n\r\nError: Error during decryption (probably incorrect key). Original error: Error: Incorrect data or key\r\n    at NodeRSA.module.exports.NodeRSA.$$decryptKey (/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:301:19)\r\n    at NodeRSA.module.exports.NodeRSA.decrypt (/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:249:21)\r\n    at Object.<anonymous> (/home/bob/staticman/decrypt.js:4:23)\r\n    at Module._compile (internal/modules/cjs/loader.js:1137:30)\r\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)\r\n    at Module.load (internal/modules/cjs/loader.js:985:32)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:878:14)\r\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\r\n    at internal/main/run_main_module.js:17:47\r\n```\r\n\r\nWhile it says probably incorrect key or data, but I've verified both, multiple times."", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'infominer33', 'comment_id': 715651841.0, 'datetime': '2020-10-24 01:28:22+00:00', 'masked_author': 'username_0', 'text': ""oh... well, I guess I was sorely mistaken about what I was doing...\r\n\r\nUnless I'm, yet again, mistaken, this setting in staticman config hashes the e-mail and the message, which is not a reversible action... which leads me to wonder.\r\n\r\n```\r\n  transforms:\r\n    email: md5\r\n    message: md5\r\n```\r\n\r\nIf that's the case, then the form asks for an e-mail address simply to make sure the user enters an e-mail, or is supposed to be used in conjunction with mailgun so you get the email address in a message sent you via mail?"", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'infominer33', 'comment_id': 715652309.0, 'datetime': '2020-10-24 01:31:57+00:00', 'masked_author': 'username_0', 'text': ""sigh.... https://github.com/eduardoboucas/staticman/issues/358 I don't suppose there's any server side logging?"", 'title': None, 'type': 'comment'}
 {'action': 'closed', 'author': 'infominer33', 'comment_id': None, 'datetime': '2020-10-24 01:32:54+00:00', 'masked_author': 'username_0', 'text': '', 'title': None, 'type': 'issue'}
 {'action': 'created', 'author': 'hispanic', 'comment_id': 715906733.0, 'datetime': '2020-10-24 12:18:02+00:00', 'masked_author': 'username_1', 'text': '@username_0 Sorry, but the logging is minimal-to-nonexistent. I was going to respond earlier that the result of the transform is a one-way hash that can\'t be reversed, but then you referenced that ""Staticman\'s Encryption Mechanism"" article and you made me doubt.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'mocza', 'comment_id': 780195160.0, 'datetime': '2021-02-16 23:57:02+00:00', 'masked_author': 'username_2', 'text': 'Hi, \r\n\r\nI keep getting a similar ""oaep decoding error"" as above in my browser console when I hit submit on a comment: \r\n_responseJSON: Object { success: false, rawError: ""Error: Error during decryption (probably incorrect key). Original error: Error: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error"" }\r\n\r\nI generated my RSA private key using:\r\n\r\n`ssh-keygen -m PEM -t rsa -b 4096 -C ""staticman key"" -f ~/.ssh/staticman_key`\r\n\r\nand I\'m running my staticman instance on Heroku with RSA_PRIVATE_KEY config var set as:\r\n\r\n`heroku config:add --app staticman-instance-name ""RSA_PRIVATE_KEY=$(cat ~/.ssh/staticman_key | tr -d \'\\n\')""`\r\n\r\nMy reCaptcha secret key was encrypted by my staticman instance using below URL form and has been populated in staticman.yml and _config.yml: \r\nhttps://${bridge_app_name}.herokuapp.com/v2/encrypt/{$recaptcha-secret}\r\n  \r\nWhat am I missing?', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'VincentTam', 'comment_id': 784347236.0, 'datetime': '2021-02-23 16:54:52+00:00', 'masked_author': 'username_3', 'text': '@username_2 The output of\r\n\r\n    cat ~/.ssh/staticman_key | tr -d \'\\n\'\r\n\r\nlacks trailing `\\n` as the 2nd part `tr -d \'\\n\'` removed all newlines, including the trailing one.  It seems that your API isn\'t happy about that.\r\n\r\nWhen I was testing <span>#</span>219 three years ago, its author advised me to use a modern code editor to replace all occurrences of the newline character `\\n` with the string `\\n`.  (You may search the hidden discussion for the ""missing RSA"").\r\n\r\nHowever, in Heroku deployment, that didn\'t work.  I used\r\n\r\n    heroku config:set RSA_PRIVATE_KEY=""$(cat key.pem)""\r\n\r\nin my [API setup guide](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/) written three years ago before the creation of the GitHub App authorization method.\r\n\r\nRecently, I\'ve found an easier method in <span>#</span>402: just copy the contents of the PEM file and paste to the right text area for `RSA_PRIVATE_KEY` through Heroku\'s online dashboard.\r\n\r\nI suggest you upgrade to v3.', 'title': None, 'type': 'comment'}]","<issue_start><issue_comment>Title: trouble decrypting encrypted comment fields
username_0: hey! I really love staticman, thanks for all the hard work to those maintaining it! 

I've enabled encryption for the e-mail field and message field to use as a regular contact form.. now I'm trying to decrypt my first contact message sent thru staticman.

first I tried:

`openssl rsautl -decrypt -in /home/bob/encrypted -out /home/bob/decrypted -inkey /home/bob/.ssh/id_bot_rsa'

outputs:
```
RSA operation error
139704754267456:error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error:../crypto/rsa/rsa_pk1.c:251:
139704754267456:error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:491:
```

then I found this post by username_3 about [Staticman's Encryption Mechanism](https://vincenttam.gitlab.io/post/2018-12-25-staticman-encryption-mechanism/) and try changing my decrypted message to base64 but getting a similar error

cat encrypted | base64 -d | openssl rsautl -decrypt -oaep -out /home/bob/decrypted -inkey /home/bob/.ssh/id_bot_rsa

```
140543979599168:error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error:../crypto/rsa/rsa_oaep.c:262:
140543979599168:error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:491:
```

I didn't realize it would be this hard, or I would have tried decrypting before I got my first submission to this contact form üòÖ

I plan to do this in python eventually.. so, I'm not married to this openssl method if you have a suggestion in a different direction.

any help appreciated
<issue_comment>username_0: Ok, trying again after finding RSA.js.. I copied it's contents to decrypt.js in the root of my staticman project folder, on the server where it's hosted and modified it for this purpose:

```
const NodeRSA = require('node-rsa')
const key = new NodeRSA()
key.importKey('-----BEGIN RSA PRIVATE KEY-----\n Key found in config.production.json \n-----END RSA PRIVATE KEY-----', 'private');
const decrypted = key.decrypt('539c27a0e4b4bfc25f45b2254245wergdsa10803f725', 'utf8');
console.log('decrypted: ', decrypted); 
```

`node decrypt.js`

outputs:

```
/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:301
            throw Error('Error during decryption (probably incorrect key). Original error: ' + e);
            ^

Error: Error during decryption (probably incorrect key). Original error: Error: Incorrect data or key
    at NodeRSA.module.exports.NodeRSA.$$decryptKey (/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:301:19)
    at NodeRSA.module.exports.NodeRSA.decrypt (/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:249:21)
    at Object.<anonymous> (/home/bob/staticman/decrypt.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

While it says probably incorrect key or data, but I've verified both, multiple times.
<issue_comment>username_0: oh... well, I guess I was sorely mistaken about what I was doing...

Unless I'm, yet again, mistaken, this setting in staticman config hashes the e-mail and the message, which is not a reversible action... which leads me to wonder.

```
  transforms:
    email: md5
    message: md5
```

If that's the case, then the form asks for an e-mail address simply to make sure the user enters an e-mail, or is supposed to be used in conjunction with mailgun so you get the email address in a message sent you via mail?
<issue_comment>username_0: sigh.... https://github.com/eduardoboucas/staticman/issues/358 I don't suppose there's any server side logging?<issue_closed>
<issue_comment>username_1: @username_0 Sorry, but the logging is minimal-to-nonexistent. I was going to respond earlier that the result of the transform is a one-way hash that can't be reversed, but then you referenced that ""Staticman's Encryption Mechanism"" article and you made me doubt.
<issue_comment>username_2: Hi, 

I keep getting a similar ""oaep decoding error"" as above in my browser console when I hit submit on a comment: 
_responseJSON: Object { success: false, rawError: ""Error: Error during decryption (probably incorrect key). Original error: Error: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error"" }

I generated my RSA private key using:

`ssh-keygen -m PEM -t rsa -b 4096 -C ""staticman key"" -f ~/.ssh/staticman_key`

and I'm running my staticman instance on Heroku with RSA_PRIVATE_KEY config var set as:

`heroku config:add --app staticman-instance-name ""RSA_PRIVATE_KEY=$(cat ~/.ssh/staticman_key | tr -d '\n')""`

My reCaptcha secret key was encrypted by my staticman instance using below URL form and has been populated in staticman.yml and _config.yml: 
https://${bridge_app_name}.herokuapp.com/v2/encrypt/{$recaptcha-secret}
  
What am I missing?
<issue_comment>username_3: @username_2 The output of

    cat ~/.ssh/staticman_key | tr -d '\n'

lacks trailing `\n` as the 2nd part `tr -d '\n'` removed all newlines, including the trailing one.  It seems that your API isn't happy about that.

When I was testing <span>#</span>219 three years ago, its author advised me to use a modern code editor to replace all occurrences of the newline character `\n` with the string `\n`.  (You may search the hidden discussion for the ""missing RSA"").

However, in Heroku deployment, that didn't work.  I used

    heroku config:set RSA_PRIVATE_KEY=""$(cat key.pem)""

in my [API setup guide](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/) written three years ago before the creation of the GitHub App authorization method.

Recently, I've found an easier method in <span>#</span>402: just copy the contents of the PEM file and paste to the right text area for `RSA_PRIVATE_KEY` through Heroku's online dashboard.

I suggest you upgrade to v3."
conda-forge/conda-forge.github.io,307208919,547,,"[{'action': 'opened', 'author': 'drorata', 'comment_id': None, 'datetime': '2018-03-21 11:34:06+00:00', 'masked_author': 'username_0', 'text': 'I tried to install `cookiecutter` and `jupyter_contrib_nbextensions` from `conda-forge`. In both cases, the last step in the plan was:\r\n\r\n```\r\nThe following packages will be DOWNGRADED:\r\n\r\n    conda:           4.5.0-py36_0                      --> 4.3.34-py36_0    conda-forge\r\n```\r\n\r\nGoing forward with this ends up with a broken `conda` installation!!!\r\n\r\nI opened an issue on https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1267 but I believe this is a more general problem given that it happens also with `cookiecutter`.', 'title': ""Installing from conda-forge breaks conda's installation"", 'type': 'issue'}
 {'action': 'created', 'author': 'jankatins', 'comment_id': 374915386.0, 'datetime': '2018-03-21 12:07:12+00:00', 'masked_author': 'username_1', 'text': 'Probably at some time fixed by https://github.com/conda-forge/conda-feedstock/pull/42', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'drorata', 'comment_id': 374921208.0, 'datetime': '2018-03-21 12:32:38+00:00', 'masked_author': 'username_0', 'text': '@username_1 What do you mean?', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'jankatins', 'comment_id': 374929176.0, 'datetime': '2018-03-21 13:04:17+00:00', 'masked_author': 'username_1', 'text': ""The problem is that conda prefers one channel over the other and will downgrade packages which are in a lower version of the preferred channel. In this case the default channel updated conda, but conda-forge has not yet done that. And you prefer the conda-forge channel above the default channel. \r\n\r\nThere are probably also nowadays ways to pin a package to a channel or so. Haven't investigated yet..."", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'CJ-Wright', 'comment_id': 374935503.0, 'datetime': '2018-03-21 13:27:00+00:00', 'masked_author': 'username_2', 'text': 'Would it be possible to post the traceback for the conda error(s) you are getting? That might give us more info on what broke.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'jakirkham', 'comment_id': 374938659.0, 'datetime': '2018-03-21 13:36:57+00:00', 'masked_author': 'username_3', 'text': 'Any reason not to use a different environment?', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'drorata', 'comment_id': 375221267.0, 'datetime': '2018-03-22 08:48:47+00:00', 'masked_author': 'username_0', 'text': '@username_2 I am not sure what you mean. What errors? As mentioned in https://github.com/conda-forge/conda-feedstock/issues/43 `conda` is no longer available after the downgrade.\r\n\r\n@username_3 I wanted to install `cookiecutter` on my base environment so it will be available across the board.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'dougalsutherland', 'comment_id': 375320726.0, 'datetime': '2018-03-22 14:13:32+00:00', 'masked_author': 'username_4', 'text': '@username_0 The problem is the `conda` shell integration; your actual installation should still be okay. See the end of https://github.com/conda-forge/conda-feedstock/issues/43#comment-375152359 for instructions on how to work around the problem until we can get the new `conda` version on conda-forge.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'sdmcclure', 'comment_id': 404222443.0, 'datetime': '2018-07-11 15:59:12+00:00', 'masked_author': 'username_5', 'text': 'Thanks for comments and help on this issue so far. I think I\'ve run into the same problem, although I appear to have an up to date version of conda. Is there a way to restore conda on my machine (Windows with Anaconda distribution).\r\n\r\nI had been using only default channels and installed the miktex package from conda-forge with:\r\nconda install -c conda-forge miktex\r\n\r\nThis upgraded and downgraded several packages now conda is not working. conda list works, but conda search gives a loading channels error and conda upgrade gives an environment error.  Conda list shows that I have version 4.5.6 with conda-forge as the channel. I tried altering my condarc file (previously empty) and specifying default first, and then conda-forge. \r\n\r\nIs there a way to restore conda so that I can continue to use the default channel? I\'m a reluctant to switch my primary channel to conda-forge until I learn more about it. I was unfamiliar with the concept of channels before I encountered this problem.\r\n\r\nHere is the error report if that\'s helpfull:\r\n\r\n`C:\\>conda update conda                                                          Solving environment: failed                                                                                                                                     # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<                                                                                                        Traceback (most recent call last):                                                File ""C:\\Anaconda3\\lib\\site-packages\\conda\\exceptions.py"", line 819, in __call__                                                                                  return func(*args, **kwargs)                                                  File ""C:\\Anaconda3\\lib\\site-packages\\conda\\cli\\main.py"", line 78, in _main                                                                                        exit_code = do_call(args, p)                                                  File ""C:\\Anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py"", line 77, in do_call                                                                            exit_code = getattr(module, func_name)(args, parser)                          File ""C:\\Anaconda3\\lib\\site-packages\\conda\\cli\\main_update.py"", line 14, in execute                                                                               install(args, parser, \'update\')                                               File ""C:\\Anaconda3\\lib\\site-packages\\conda\\cli\\install.py"", line 235, in install                                                                                  force_reinstall=context.force,                                                File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\solve.py"", line 506, in solve_for_transaction                                                                     force_remove, force_reinstall)                                                File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\solve.py"", line 439, in solve_for_diff                                                                            final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)                                                                       File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\solve.py"", line 180, in solve_final_state                                                                         index, r = self._prepare(prepared_specs)                                      File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\solve.py"", line 580, in _prepare                                                                                  self.subdirs, prepared_specs)                                                 File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\index.py"", line 215, in get_reduced_index                                                                         new_records = query_all(spec)                                                 File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\index.py"", line 184, in query_all                                                                                 return tuple(concat(future.result() for future in as_completed(futures)))                                                                                     File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py"", line 94, in query                                                                                self.load()                                                                   File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py"", line 148, in load                                                                                _internal_state = self._load()                                                File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py"", line 216, in _load                                                                               mod_etag_headers.get(\'_mod\'))                                                 File ""C:\\Anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py"", line 416, in fetch_repodata_remote_request                                                       timeout=timeout)                                                              File ""C:\\Anaconda3\\lib\\site-packages\\requests\\sessions.py"", line 501, in get                                                                                      return self.request(\'GET\', url, **kwargs)                                     File ""C:\\Anaconda3\\lib\\site-packages\\requests\\sessions.py"", line 479, in request                                                                                  prep.url, proxies, stream, verify, cert                                       File ""C:\\Anaconda3\\lib\\site-packages\\requests\\sessions.py"", line 654, in merge_environment_settings                                                               env_proxies = get_environ_proxies(url) or {}                                  File ""C:\\Anaconda3\\lib\\site-packages\\requests\\utils.py"", line 617, in get_environ_proxies                                                                         if should_bypass_proxies(url):                                              TypeError: should_bypass_proxies_patched() missing 1 required positional argument: \'no_proxy\'                                                                                                                                               `$ C:\\Anaconda3\\Scripts\\conda update conda`                                                                                                                       environment variables:                                                                         CIO_TEST=<not set>                                                            CONDA_ROOT=C:\\Anaconda3                                                           HOMEPATH=\\                                                                          PATH=C:\\Anaconda3\\Library\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Progra                                                                                          m Files\\Common Files\\Microsoft Shared\\Windows Live;C:\\Program Files                                                                                             (x86)\\Common Files\\Microsoft Shared\\Windows Live;c:\\Program Files                                                                                               (x86)\\AMD APP\\bin\\x86_64;c:\\Program Files (x86)\\AMD                             APP\\bin\\x86;c:\\Program Files (x86)\\Intel\\iCLS Client\\;c:\\Program                                                                                                Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\Sys                                                                                          tem32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;c:\\Program                                                                                               Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files                                                                                               (x86)\\Windows Live\\Shared;C:\\GWV6\\;C:\\GWV6\\gdal\\bin;C:\\Program                                                                                                  Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program                                                                                                Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files                                                                                          (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files                                                                                          (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Anaconda3;C:\\                                                                                          Anaconda3\\Scripts;C:\\Anaconda3\\Library\\bin;C:\\Program                           Files\\Git\\cmd;%MAINDIR%                                            PSMODULEPATH=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\          REQUESTS_CA_BUNDLE=<not set>                                                         SSL_CERT_FILE=<not set>                                                                                                                                  active environment : None                                                         user config file : C:\\Users\\smcclure\\.condarc                             populated config files : C:\\Users\\smcclure\\.condarc                                      conda version : 4.5.6                                                     conda-build version : 1.20.0                                                         python version : 3.5.1.final.0                                                base environment : C:\\Anaconda3  (writable)                                         channel URLs : https://repo.anaconda.com/pkgs/main/win-64                                      https://repo.anaconda.com/pkgs/main/noarch                                      https://repo.anaconda.com/pkgs/free/win-64                                      https://repo.anaconda.com/pkgs/free/noarch                                      https://repo.anaconda.com/pkgs/r/win-64                                         https://repo.anaconda.com/pkgs/r/noarch                                         https://repo.anaconda.com/pkgs/pro/win-64                                       https://repo.anaconda.com/pkgs/pro/noarch                                       https://repo.anaconda.com/pkgs/msys2/win-64                                     https://repo.anaconda.com/pkgs/msys2/noarch                                     https://conda.anaconda.org/conda-forge/win-64                                   https://conda.anaconda.org/conda-forge/noarch                   package cache : C:\\Anaconda3\\pkgs                                                               C:\\Users\\smcclure\\AppData\\Local\\conda\\conda\\pkgs             envs directories : C:\\Anaconda3\\envs                                                               C:\\Users\\smcclure\\AppData\\Local\\conda\\conda\\envs                                C:\\Users\\smcclure\\.conda\\envs                                        platform : win-64                                                             user-agent : conda/4.5.6 requests/2.12.4 CPython/3.5.1 Windows/7 Windows/6.1.7601                                                                            administrator : False                                                              netrc file : None                                                             offline mode : False                                                                                                                                                                                                                 An unexpected error has occurred. Conda has prepared the above report.          If submitted, this report will be used by core maintainers to improve           future releases of conda.                                                       Would you like conda to send this report to the core maintainers?               [y/N]: y                                                                        Upload did not complete.                                                        Thank you for helping to improve conda.                                         Opt-in to always sending reports (and not see this message again)               by running                                                                                                                                                          $ conda config --set report_errors true `', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'CJ-Wright', 'comment_id': 404229610.0, 'datetime': '2018-07-11 16:21:55+00:00', 'masked_author': 'username_2', 'text': ""@username_5 Would it be possible to re-format the traceback that you posted? It is very difficult to read in it's current format."", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'sdmcclure', 'comment_id': 404235782.0, 'datetime': '2018-07-11 16:43:03+00:00', 'masked_author': 'username_5', 'text': ""Sorry for the poor formatting initially. Hopefully it's more legible now"", 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'CJ-Wright', 'comment_id': 404236992.0, 'datetime': '2018-07-11 16:47:14+00:00', 'masked_author': 'username_2', 'text': '@username_5 is it possible to also post the current env? (`conda list`)?\r\nI suspect that his has to do with `requests` going `noarch`.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'sdmcclure', 'comment_id': 404260991.0, 'datetime': '2018-07-11 18:08:04+00:00', 'masked_author': 'username_5', 'text': 'Sure:\r\n\r\n```\r\nC:\\>conda list                                                                \r\n# packages in environment at C:\\Anaconda3:                                    #                                                                             # Name                    Version                   Build  Channel            \r\nalabaster                 0.7.7                    py35_0                     \r\nanaconda                  custom           py35h64770cb_0                     \r\nanaconda-client           1.4.0                    py35_0                     \r\nanaconda-navigator        1.8.4                    py35_0                     \r\nanaconda-project          0.8.2            py35h06aeb26_0                     \r\nargcomplete               1.0.0                    py35_1                     \r\nastroid                   1.6.5                    py35_0                     \r\nastropy                   2.0.7            py35h452e1ab_1                     \r\nbabel                     2.2.0                    py35_0                     \r\nbeautifulsoup4            4.4.1                    py35_0                     \r\nbitarray                  0.8.1                    py35_1                     \r\nblaze                     0.9.1                    py35_0                     \r\nbleach                    2.1.3                    py35_0                     \r\nblosc                     1.14.3               he51fdeb_0                     \r\nbokeh                     0.11.1                   py35_0                     \r\nboost                     1.66.0              py35_vc14_1  [vc14]  conda-forge\r\nboost-cpp                 1.66.0                   vc14_1  [vc14]  conda-forge\r\nboto                      2.39.0                   py35_0                     \r\nbottleneck                1.2.1            py35h8a3671c_0                     \r\nbzip2                     1.0.6                    vc14_1  [vc14]  conda-forge\r\nca-certificates           2018.4.16                     0    conda-forge      \r\ncertifi                   2018.4.16                py35_0    conda-forge      \r\ncffi                      1.5.2                    py35_0                     \r\nchardet                   3.0.4            py35h177e1b7_1                     \r\nchest                     0.2.3                    py35_0                     \r\nclick                     6.7              py35h10df73f_0                     \r\nclick-plugins             1.0.3                    py35_0                     \r\ncligj                     0.4.0                    py35_0                     \r\ncloudpickle               0.1.1                    py35_0                     \r\nclyent                    1.2.1                    py35_0                     \r\ncolorama                  0.3.7                    py35_0                     \r\ncomtypes                  1.1.2                    py35_0                     \r\nconda                     4.5.6                    py35_0    conda-forge      \r\nconda-build               1.20.0                   py35_0                     \r\nconda-env                 2.6.0                h36134e3_1                     \r\nconda-manager             0.4.0                    py35_0                     \r\nconfigobj                 5.0.6                    py35_0                     \r\nconsole_shortcut          0.1.1                    py35_1                     \r\ncryptography              1.7.1                    py35_0                     \r\ncurl                      7.60.0                   vc14_0  [vc14]  conda-forge\r\ncycler                    0.10.0                   py35_0                     \r\ncython                    0.23.4                   py35_0                     \r\ncytoolz                   0.9.0.1          py35hfa6e2cd_0                     \r\ndask                      0.8.1                    py35_0                     \r\ndatashape                 0.5.1                    py35_0                     \r\ndecorator                 4.0.9                    py35_0                     \r\ndescartes                 1.1.0                    py35_0                    \r\ndill                      0.2.4                    py35_0                     \r\ndocutils                  0.14             py35h8ccb97f_0                     \r\ndynd-python               0.7.2                    py35_0                     \r\nentrypoints               0.2.3            py35hb91ced9_2                     \r\net_xmlfile                1.0.1                    py35_0                     \r\nexpat                     2.2.5                    vc14_0  [vc14]  conda-forge\r\nfastcache                 1.0.2                    py35_0                     \r\nfiona                     1.7.10           py35hefe5c53_0                     \r\nflask                     0.10.1                   py35_1                     \r\nflask-cors                2.1.2                    py35_0                    \r\n flopy                     3.2.4                     <pip>                     \r\nfreetype                  2.8.1                    vc14_0  [vc14]  conda-forge\r\nfreexl                    1.0.2                    vc14_2  [vc14]  conda-forge\r\ngdal                      2.2.2            py35h202a4aa_1                     \r\ngeopandas                 0.3.0                    py35_0                     \r\ngeos                      3.6.2                h9ef7328_2                     \r\ngeotiff                   1.4.2                    vc14_1  [vc14]  conda-forge\r\ngevent                    1.1.0                    py35_0                     \r\ngreenlet                  0.4.9                    py35_0                     \r\nh5py                      2.8.0            py35hfa6e2cd_0    conda-forge      \r\nhdf4                      4.2.13                   vc14_0  [vc14]  conda-forge\r\nhdf5                      1.10.1                   vc14_2  [vc14]  conda-forge\r\nheapdict                  1.0.0                    py35_0                     \r\nhtml5lib                  1.0.1            py35h047fa9f_0                     \r\nicc_rt                    2017.0.4             h97af966_0                     \r\nicu                       58.2                     vc14_0  [vc14]  conda-forge\r\nidna                      2.0                      py35_0                     \r\nimageio                   2.3.0                    py35_0                     \r\n[Truncated]\ntoolz                     0.9.0                    py35_0                     \r\ntornado                   4.3                      py35_0                     \r\ntraitlets                 4.2.1                    py35_0                     \r\nunicodecsv                0.14.1                   py35_0                     \r\nvc                        14                            0                     \r\nvs2015_runtime            14.00.23026.0                 0                     \r\nwebencodings              0.5.1            py35h5d527fb_1                     \r\nwerkzeug                  0.11.4                   py35_0                     \r\nwheel                     0.29.0                   py35_0                     \r\nwincertstore              0.2              py35hfebbdb8_0                     \r\nwrapt                     1.10.11          py35h54666f7_0                     \r\nxerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge\r\nxlrd                      0.9.4                    py35_0                     \r\nxlsxwriter                0.8.4                    py35_0                     \r\nxlwings                   0.7.0                    py35_0                     \r\nxlwt                      1.0.0                    py35_0                     \r\nxz                        5.2.4                h2fa13f4_4                     \r\nzlib                      1.2.11                   vc14_0  [vc14]  conda-forge\r\n\r\n```', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'isuruf', 'comment_id': 404262640.0, 'datetime': '2018-07-11 18:14:03+00:00', 'masked_author': 'username_6', 'text': 'https://github.com/conda/conda/issues/7524. Original issue is fixed now', 'title': None, 'type': 'comment'}
 {'action': 'closed', 'author': 'isuruf', 'comment_id': None, 'datetime': '2018-07-11 18:14:03+00:00', 'masked_author': 'username_6', 'text': '', 'title': None, 'type': 'issue'}
 {'action': 'created', 'author': 'sdmcclure', 'comment_id': 404295074.0, 'datetime': '2018-07-11 20:11:24+00:00', 'masked_author': 'username_5', 'text': '@username_6 Thanks! This solution worked for me.', 'title': None, 'type': 'comment'}
 {'action': 'created', 'author': 'DonAurelio', 'comment_id': 529065279.0, 'datetime': '2019-09-07 02:48:31+00:00', 'masked_author': 'username_7', 'text': 'I solve this problem installing the version 4.6.14 of conda as suggested on this issue [9004](https://github.com/conda/conda/issues/9004) before perform further installs.\r\n\r\n`conda install conda=4.6.14\r\n`\r\nIt looks like further versions of conda are introducing this error.', 'title': None, 'type': 'comment'}]","<issue_start><issue_comment>Title: Installing from conda-forge breaks conda's installation
username_0: I tried to install `cookiecutter` and `jupyter_contrib_nbextensions` from `conda-forge`. In both cases, the last step in the plan was:

```
The following packages will be DOWNGRADED:

    conda:           4.5.0-py36_0                      --> 4.3.34-py36_0    conda-forge
```

Going forward with this ends up with a broken `conda` installation!!!

I opened an issue on https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1267 but I believe this is a more general problem given that it happens also with `cookiecutter`.
<issue_comment>username_1: Probably at some time fixed by https://github.com/conda-forge/conda-feedstock/pull/42
<issue_comment>username_0: @username_1 What do you mean?
<issue_comment>username_1: The problem is that conda prefers one channel over the other and will downgrade packages which are in a lower version of the preferred channel. In this case the default channel updated conda, but conda-forge has not yet done that. And you prefer the conda-forge channel above the default channel. 

There are probably also nowadays ways to pin a package to a channel or so. Haven't investigated yet...
<issue_comment>username_2: Would it be possible to post the traceback for the conda error(s) you are getting? That might give us more info on what broke.
<issue_comment>username_3: Any reason not to use a different environment?
<issue_comment>username_0: @username_2 I am not sure what you mean. What errors? As mentioned in https://github.com/conda-forge/conda-feedstock/issues/43 `conda` is no longer available after the downgrade.

@username_3 I wanted to install `cookiecutter` on my base environment so it will be available across the board.
<issue_comment>username_4: @username_0 The problem is the `conda` shell integration; your actual installation should still be okay. See the end of https://github.com/conda-forge/conda-feedstock/issues/43#comment-375152359 for instructions on how to work around the problem until we can get the new `conda` version on conda-forge.
<issue_comment>username_5: Thanks for comments and help on this issue so far. I think I've run into the same problem, although I appear to have an up to date version of conda. Is there a way to restore conda on my machine (Windows with Anaconda distribution).

I had been using only default channels and installed the miktex package from conda-forge with:
conda install -c conda-forge miktex

This upgraded and downgraded several packages now conda is not working. conda list works, but conda search gives a loading channels error and conda upgrade gives an environment error.  Conda list shows that I have version 4.5.6 with conda-forge as the channel. I tried altering my condarc file (previously empty) and specifying default first, and then conda-forge. 

Is there a way to restore conda so that I can continue to use the default channel? I'm a reluctant to switch my primary channel to conda-forge until I learn more about it. I was unfamiliar with the concept of channels before I encountered this problem.

Here is the error report if that's helpfull:

`C:\>conda update conda                                                          Solving environment: failed                                                                                                                                     # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<                                                                                                        Traceback (most recent call last):                                                File ""C:\Anaconda3\lib\site-packages\conda\exceptions.py"", line 819, in __call__                                                                                  return func(*args, **kwargs)                                                  File ""C:\Anaconda3\lib\site-packages\conda\cli\main.py"", line 78, in _main                                                                                        exit_code = do_call(args, p)                                                  File ""C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py"", line 77, in do_call                                                                            exit_code = getattr(module, func_name)(args, parser)                          File ""C:\Anaconda3\lib\site-packages\conda\cli\main_update.py"", line 14, in execute                                                                               install(args, parser, 'update')                                               File ""C:\Anaconda3\lib\site-packages\conda\cli\install.py"", line 235, in install                                                                                  force_reinstall=context.force,                                                File ""C:\Anaconda3\lib\site-packages\conda\core\solve.py"", line 506, in solve_for_transaction                                                                     force_remove, force_reinstall)                                                File ""C:\Anaconda3\lib\site-packages\conda\core\solve.py"", line 439, in solve_for_diff                                                                            final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)                                                                       File ""C:\Anaconda3\lib\site-packages\conda\core\solve.py"", line 180, in solve_final_state                                                                         index, r = self._prepare(prepared_specs)                                      File ""C:\Anaconda3\lib\site-packages\conda\core\solve.py"", line 580, in _prepare                                                                                  self.subdirs, prepared_specs)                                                 File ""C:\Anaconda3\lib\site-packages\conda\core\index.py"", line 215, in get_reduced_index                                                                         new_records = query_all(spec)                                                 File ""C:\Anaconda3\lib\site-packages\conda\core\index.py"", line 184, in query_all                                                                                 return tuple(concat(future.result() for future in as_completed(futures)))                                                                                     File ""C:\Anaconda3\lib\site-packages\conda\core\subdir_data.py"", line 94, in query                                                                                self.load()                                                                   File ""C:\Anaconda3\lib\site-packages\conda\core\subdir_data.py"", line 148, in load                                                                                _internal_state = self._load()                                                File ""C:\Anaconda3\lib\site-packages\conda\core\subdir_data.py"", line 216, in _load                                                                               mod_etag_headers.get('_mod'))                                                 File ""C:\Anaconda3\lib\site-packages\conda\core\subdir_data.py"", line 416, in fetch_repodata_remote_request                                                       timeout=timeout)                                                              File ""C:\Anaconda3\lib\site-packages\requests\sessions.py"", line 501, in get                                                                                      return self.request('GET', url, **kwargs)                                     File ""C:\Anaconda3\lib\site-packages\requests\sessions.py"", line 479, in request                                                                                  prep.url, proxies, stream, verify, cert                                       File ""C:\Anaconda3\lib\site-packages\requests\sessions.py"", line 654, in merge_environment_settings                                                               env_proxies = get_environ_proxies(url) or {}                                  File ""C:\Anaconda3\lib\site-packages\requests\utils.py"", line 617, in get_environ_proxies                                                                         if should_bypass_proxies(url):                                              TypeError: should_bypass_proxies_patched() missing 1 required positional argument: 'no_proxy'                                                                                                                                               `$ C:\Anaconda3\Scripts\conda update conda`                                                                                                                       environment variables:                                                                         CIO_TEST=<not set>                                                            CONDA_ROOT=C:\Anaconda3                                                           HOMEPATH=\                                                                          PATH=C:\Anaconda3\Library\bin;C:\ProgramData\Oracle\Java\javapath;C:\Progra                                                                                          m Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files                                                                                             (x86)\Common Files\Microsoft Shared\Windows Live;c:\Program Files                                                                                               (x86)\AMD APP\bin\x86_64;c:\Program Files (x86)\AMD                             APP\bin\x86;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program                                                                                                Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\Sys                                                                                          tem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program                                                                                               Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files                                                                                               (x86)\Windows Live\Shared;C:\GWV6\;C:\GWV6\gdal\bin;C:\Program                                                                                                  Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program                                                                                                Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files                                                                                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files                                                                                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Anaconda3;C:\                                                                                          Anaconda3\Scripts;C:\Anaconda3\Library\bin;C:\Program                           Files\Git\cmd;%MAINDIR%                                            PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\          REQUESTS_CA_BUNDLE=<not set>                                                         SSL_CERT_FILE=<not set>                                                                                                                                  active environment : None                                                         user config file : C:\Users\smcclure\.condarc                             populated config files : C:\Users\smcclure\.condarc                                      conda version : 4.5.6                                                     conda-build version : 1.20.0                                                         python version : 3.5.1.final.0                                                base environment : C:\Anaconda3  (writable)                                         channel URLs : https://repo.anaconda.com/pkgs/main/win-64                                      https://repo.anaconda.com/pkgs/main/noarch                                      https://repo.anaconda.com/pkgs/free/win-64                                      https://repo.anaconda.com/pkgs/free/noarch                                      https://repo.anaconda.com/pkgs/r/win-64                                         https://repo.anaconda.com/pkgs/r/noarch                                         https://repo.anaconda.com/pkgs/pro/win-64                                       https://repo.anaconda.com/pkgs/pro/noarch                                       https://repo.anaconda.com/pkgs/msys2/win-64                                     https://repo.anaconda.com/pkgs/msys2/noarch                                     https://conda.anaconda.org/conda-forge/win-64                                   https://conda.anaconda.org/conda-forge/noarch                   package cache : C:\Anaconda3\pkgs                                                               C:\Users\smcclure\AppData\Local\conda\conda\pkgs             envs directories : C:\Anaconda3\envs                                                               C:\Users\smcclure\AppData\Local\conda\conda\envs                                C:\Users\smcclure\.conda\envs                                        platform : win-64                                                             user-agent : conda/4.5.6 requests/2.12.4 CPython/3.5.1 Windows/7 Windows/6.1.7601                                                                            administrator : False                                                              netrc file : None                                                             offline mode : False                                                                                                                                                                                                                 An unexpected error has occurred. Conda has prepared the above report.          If submitted, this report will be used by core maintainers to improve           future releases of conda.                                                       Would you like conda to send this report to the core maintainers?               [y/N]: y                                                                        Upload did not complete.                                                        Thank you for helping to improve conda.                                         Opt-in to always sending reports (and not see this message again)               by running                                                                                                                                                          $ conda config --set report_errors true `
<issue_comment>username_2: @username_5 Would it be possible to re-format the traceback that you posted? It is very difficult to read in it's current format.
<issue_comment>username_5: Sorry for the poor formatting initially. Hopefully it's more legible now
<issue_comment>username_2: @username_5 is it possible to also post the current env? (`conda list`)?
I suspect that his has to do with `requests` going `noarch`.
<issue_comment>username_5: Sure:

```
C:\>conda list                                                                
# packages in environment at C:\Anaconda3:                                    #                                                                             # Name                    Version                   Build  Channel            
alabaster                 0.7.7                    py35_0                     
anaconda                  custom           py35h64770cb_0                     
anaconda-client           1.4.0                    py35_0                     
anaconda-navigator        1.8.4                    py35_0                     
anaconda-project          0.8.2            py35h06aeb26_0                     
argcomplete               1.0.0                    py35_1                     
astroid                   1.6.5                    py35_0                     
astropy                   2.0.7            py35h452e1ab_1                     
babel                     2.2.0                    py35_0                     
beautifulsoup4            4.4.1                    py35_0                     
bitarray                  0.8.1                    py35_1                     
blaze                     0.9.1                    py35_0                     
bleach                    2.1.3                    py35_0                     
blosc                     1.14.3               he51fdeb_0                     
bokeh                     0.11.1                   py35_0                     
boost                     1.66.0              py35_vc14_1  [vc14]  conda-forge
boost-cpp                 1.66.0                   vc14_1  [vc14]  conda-forge
boto                      2.39.0                   py35_0                     
bottleneck                1.2.1            py35h8a3671c_0                     
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2018.4.16                     0    conda-forge      
certifi                   2018.4.16                py35_0    conda-forge      
cffi                      1.5.2                    py35_0                     
chardet                   3.0.4            py35h177e1b7_1                     
chest                     0.2.3                    py35_0                     
click                     6.7              py35h10df73f_0                     
click-plugins             1.0.3                    py35_0                     
cligj                     0.4.0                    py35_0                     
cloudpickle               0.1.1                    py35_0                     
clyent                    1.2.1                    py35_0                     
colorama                  0.3.7                    py35_0                     
comtypes                  1.1.2                    py35_0                     
conda                     4.5.6                    py35_0    conda-forge      
conda-build               1.20.0                   py35_0                     
conda-env                 2.6.0                h36134e3_1                     
conda-manager             0.4.0                    py35_0                     
configobj                 5.0.6                    py35_0                     
console_shortcut          0.1.1                    py35_1                     
cryptography              1.7.1                    py35_0                     
curl                      7.60.0                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                   py35_0                     
cython                    0.23.4                   py35_0                     
cytoolz                   0.9.0.1          py35hfa6e2cd_0                     
dask                      0.8.1                    py35_0                     
datashape                 0.5.1                    py35_0                     
decorator                 4.0.9                    py35_0                     
descartes                 1.1.0                    py35_0                    
dill                      0.2.4                    py35_0                     
docutils                  0.14             py35h8ccb97f_0                     
dynd-python               0.7.2                    py35_0                     
entrypoints               0.2.3            py35hb91ced9_2                     
et_xmlfile                1.0.1                    py35_0                     
expat                     2.2.5                    vc14_0  [vc14]  conda-forge
fastcache                 1.0.2                    py35_0                     
fiona                     1.7.10           py35hefe5c53_0                     
flask                     0.10.1                   py35_1                     
flask-cors                2.1.2                    py35_0                    
 flopy                     3.2.4                     <pip>                     
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
freexl                    1.0.2                    vc14_2  [vc14]  conda-forge
gdal                      2.2.2            py35h202a4aa_1                     
geopandas                 0.3.0                    py35_0                     
geos                      3.6.2                h9ef7328_2                     
geotiff                   1.4.2                    vc14_1  [vc14]  conda-forge
gevent                    1.1.0                    py35_0                     
greenlet                  0.4.9                    py35_0                     
h5py                      2.8.0            py35hfa6e2cd_0    conda-forge      
hdf4                      4.2.13                   vc14_0  [vc14]  conda-forge
hdf5                      1.10.1                   vc14_2  [vc14]  conda-forge
heapdict                  1.0.0                    py35_0                     
html5lib                  1.0.1            py35h047fa9f_0                     
icc_rt                    2017.0.4             h97af966_0                     
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.0                      py35_0                     
imageio                   2.3.0                    py35_0                     
[Truncated]
toolz                     0.9.0                    py35_0                     
tornado                   4.3                      py35_0                     
traitlets                 4.2.1                    py35_0                     
unicodecsv                0.14.1                   py35_0                     
vc                        14                            0                     
vs2015_runtime            14.00.23026.0                 0                     
webencodings              0.5.1            py35h5d527fb_1                     
werkzeug                  0.11.4                   py35_0                     
wheel                     0.29.0                   py35_0                     
wincertstore              0.2              py35hfebbdb8_0                     
wrapt                     1.10.11          py35h54666f7_0                     
xerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge
xlrd                      0.9.4                    py35_0                     
xlsxwriter                0.8.4                    py35_0                     
xlwings                   0.7.0                    py35_0                     
xlwt                      1.0.0                    py35_0                     
xz                        5.2.4                h2fa13f4_4                     
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

```
<issue_comment>username_6: https://github.com/conda/conda/issues/7524. Original issue is fixed now<issue_closed>
<issue_comment>username_5: @username_6 Thanks! This solution worked for me.
<issue_comment>username_7: I solve this problem installing the version 4.6.14 of conda as suggested on this issue [9004](https://github.com/conda/conda/issues/9004) before perform further installs.

`conda install conda=4.6.14
`
It looks like further versions of conda are introducing this error."
protocol/nft-website,1070176190,170,,"[{'action': 'opened', 'author': 'ItsAJeepThing', 'comment_id': None, 'datetime': '2021-12-03 03:15:02+00:00', 'masked_author': 'username_0', 'text': 'https://youtu.be/Obnxs_GC9Bk', 'title': '[CR] If using IPFS add a web3 storage API to the Smart contract.', 'type': 'issue'}
 {'action': 'created', 'author': 'ItsAJeepThing', 'comment_id': 985820003.0, 'datetime': '2021-12-03 20:52:10+00:00', 'masked_author': 'username_0', 'text': '#Theta blockchain claims they have a unique solution...that their #web3 decentralized video streaming/storage API can and should be used for NFT data storage.\r\n\r\nhttps://medium.com/theta-network/new-theta-video-api-service-gives-developers-power-to-bring-web-3-0-20bada2b1fab', 'title': None, 'type': 'comment'}]","<issue_start><issue_comment>Title: [CR] If using IPFS add a web3 storage API to the Smart contract.
username_0: https://youtu.be/Obnxs_GC9Bk
<issue_comment>username_0: #Theta blockchain claims they have a unique solution...that their #web3 decentralized video streaming/storage API can and should be used for NFT data storage.

https://medium.com/theta-network/new-theta-video-api-service-gives-developers-power-to-bring-web-3-0-20bada2b1fab"
KiCad/kicad-website,390194397,359,,"[{'action': 'opened', 'author': 'poeschlr', 'comment_id': None, 'datetime': '2018-12-12 12:00:41+00:00', 'masked_author': 'username_0', 'text': 'The wording for this exception is a bit strange. Right now it could be read that these should not be stacked while the intention is to only inform the reader that the invisible pins of such a stack should use the electrical type passive.\r\n\r\nThe reason for why this must be done is also wrong for power input. (It does not create a problem with ERC. It is an exception to avoid these pins to be global labels.)', 'title': '[KLC] better wording for stacking of power output, output and power input pins', 'type': 'issue'}
 {'action': 'closed', 'author': 'marekr', 'comment_id': None, 'datetime': '2018-12-22 16:45:15+00:00', 'masked_author': 'username_1', 'text': '', 'title': None, 'type': 'issue'}]","<issue_start><issue_comment>Title: [KLC] better wording for stacking of power output, output and power input pins
username_0: The wording for this exception is a bit strange. Right now it could be read that these should not be stacked while the intention is to only inform the reader that the invisible pins of such a stack should use the electrical type passive.

The reason for why this must be done is also wrong for power input. (It does not create a problem with ERC. It is an exception to avoid these pins to be global labels.)<issue_closed>"
devopsdays/devopsdays-web,116211172,8,,"[{'action': 'opened', 'author': 'mattstratton', 'comment_id': None, 'datetime': '2015-11-10 21:56:39+00:00', 'masked_author': 'username_0', 'text': 'This is a low priority, but once we have the format down, we should create a pair of shell (and Powershell) scripts that can be used to generate a new event, taking in just the year and city name, etc.\r\n\r\nIn psuedocode, something like this (taking $YEAR and $CITY as arguments or something)\r\n\r\n```\r\nhugo new events/$YEAR-$CITY/welcome.md --kind event\r\nhugo new events/$YEAR-$CITY/program.md --kind event\r\nhugo new events/$YEAR-$CITY/contact.md --kind event\r\nhugo new events/$YEAR-$CITY/conduct.md --kind event\r\n.\r\n.\r\n.\r\ncp data/events/TEMPLATE.yml data/events/$YEAR-$CITY.yml\r\n```', 'title': 'Create setup script for new events', 'type': 'issue'}
 {'action': 'closed', 'author': 'bridgetkromhout', 'comment_id': None, 'datetime': '2016-05-08 12:41:05+00:00', 'masked_author': 'username_1', 'text': '', 'title': None, 'type': 'issue'}
 {'action': 'created', 'author': 'bridgetkromhout', 'comment_id': 217716117.0, 'datetime': '2016-05-08 12:41:05+00:00', 'masked_author': 'username_1', 'text': ""Closing this, as I've done it."", 'title': None, 'type': 'comment'}]","<issue_start><issue_comment>Title: Create setup script for new events
username_0: This is a low priority, but once we have the format down, we should create a pair of shell (and Powershell) scripts that can be used to generate a new event, taking in just the year and city name, etc.

In psuedocode, something like this (taking $YEAR and $CITY as arguments or something)

```
hugo new events/$YEAR-$CITY/welcome.md --kind event
hugo new events/$YEAR-$CITY/program.md --kind event
hugo new events/$YEAR-$CITY/contact.md --kind event
hugo new events/$YEAR-$CITY/conduct.md --kind event
.
.
.
cp data/events/TEMPLATE.yml data/events/$YEAR-$CITY.yml
```<issue_closed>
<issue_comment>username_1: Closing this, as I've done it."
